classdef ropod_sem_waypoint < robotics.ros.Message
    %ropod_sem_waypoint MATLAB implementation of ropod_ros_msgs/ropod_sem_waypoint
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2018 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'ropod_ros_msgs/ropod_sem_waypoint' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '3bbc9f4ace639a3fab55685f6bc8507a' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        Command
        Location
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Command', 'Location'} % List of non-constant message properties
        ROSPropertyList = {'command', 'location'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = ropod_sem_waypoint(msg)
            %ropod_sem_waypoint Construct the message object ropod_sem_waypoint
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function command = get.Command(obj)
            %get.Command Get the value for property Command
            command = char(obj.JavaMessage.getCommand);
        end
        
        function set.Command(obj, command)
            %set.Command Set the value for property Command
            validateattributes(command, {'char'}, {}, 'ropod_sem_waypoint', 'Command');
            
            obj.JavaMessage.setCommand(command);
        end
        
        function location = get.Location(obj)
            %get.Location Get the value for property Location
            location = char(obj.JavaMessage.getLocation);
        end
        
        function set.Location(obj, location)
            %set.Location Set the value for property Location
            validateattributes(location, {'char'}, {}, 'ropod_sem_waypoint', 'Location');
            
            obj.JavaMessage.setLocation(location);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.Command = obj.Command;
            cpObj.Location = obj.Location;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Command = strObj.Command;
            obj.Location = strObj.Location;
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Command = obj.Command;
            strObj.Location = obj.Location;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.ropod_ros_msgs.ropod_sem_waypoint.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.ropod_ros_msgs.ropod_sem_waypoint;
            obj.reload(strObj);
        end
    end
end
