classdef ropod_demo_plan < robotics.ros.Message
    %ropod_demo_plan MATLAB implementation of ropod_ros_msgs/ropod_demo_plan
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2018 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'ropod_ros_msgs/ropod_demo_plan' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = 'f07c615c9ecdfb9def7fe5f0176a465f' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        RopodRosMsgsRopodDemoLocationClass = robotics.ros.msg.internal.MessageFactory.getClassForType('ropod_ros_msgs/ropod_demo_location') % Dispatch to MATLAB class for message type ropod_ros_msgs/ropod_demo_location
        StdMsgsHeaderClass = robotics.ros.msg.internal.MessageFactory.getClassForType('std_msgs/Header') % Dispatch to MATLAB class for message type std_msgs/Header
    end
    
    properties (Dependent)
        Header
        PlanID
        Locations
    end
    
    properties (Access = protected)
        Cache = struct('Header', [], 'Locations', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Header', 'Locations', 'PlanID'} % List of non-constant message properties
        ROSPropertyList = {'header', 'locations', 'planID'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = ropod_demo_plan(msg)
            %ropod_demo_plan Construct the message object ropod_demo_plan
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function header = get.Header(obj)
            %get.Header Get the value for property Header
            if isempty(obj.Cache.Header)
                obj.Cache.Header = feval(obj.StdMsgsHeaderClass, obj.JavaMessage.getHeader);
            end
            header = obj.Cache.Header;
        end
        
        function set.Header(obj, header)
            %set.Header Set the value for property Header
            validateattributes(header, {obj.StdMsgsHeaderClass}, {'nonempty', 'scalar'}, 'ropod_demo_plan', 'Header');
            
            obj.JavaMessage.setHeader(header.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Header)
                obj.Cache.Header.setJavaObject(header.getJavaObject);
            end
        end
        
        function planid = get.PlanID(obj)
            %get.PlanID Get the value for property PlanID
            planid = char(obj.JavaMessage.getPlanID);
        end
        
        function set.PlanID(obj, planid)
            %set.PlanID Set the value for property PlanID
            validateattributes(planid, {'char'}, {}, 'ropod_demo_plan', 'PlanID');
            
            obj.JavaMessage.setPlanID(planid);
        end
        
        function locations = get.Locations(obj)
            %get.Locations Get the value for property Locations
            if isempty(obj.Cache.Locations)
                javaArray = obj.JavaMessage.getLocations;
                array = obj.readJavaArray(javaArray, obj.RopodRosMsgsRopodDemoLocationClass);
                obj.Cache.Locations = feval(obj.RopodRosMsgsRopodDemoLocationClass, array);
            end
            locations = obj.Cache.Locations;
        end
        
        function set.Locations(obj, locations)
            %set.Locations Set the value for property Locations
            if ~isvector(locations) && isempty(locations)
                % Allow empty [] input
                locations = feval([obj.RopodRosMsgsRopodDemoLocationClass '.empty'], 0, 1);
            end
            
            validateattributes(locations, {obj.RopodRosMsgsRopodDemoLocationClass}, {'vector'}, 'ropod_demo_plan', 'Locations');
            
            javaArray = obj.JavaMessage.getLocations;
            array = obj.writeJavaArray(locations, javaArray, obj.RopodRosMsgsRopodDemoLocationClass);
            obj.JavaMessage.setLocations(array);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Locations)
                obj.Cache.Locations = [];
                obj.Cache.Locations = obj.Locations;
            end
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.Header = [];
            obj.Cache.Locations = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.PlanID = obj.PlanID;
            
            % Recursively copy compound properties
            cpObj.Header = copy(obj.Header);
            cpObj.Locations = copy(obj.Locations);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.PlanID = strObj.PlanID;
            obj.Header = feval([obj.StdMsgsHeaderClass '.loadobj'], strObj.Header);
            LocationsCell = arrayfun(@(x) feval([obj.RopodRosMsgsRopodDemoLocationClass '.loadobj'], x), strObj.Locations, 'UniformOutput', false);
            obj.Locations = vertcat(LocationsCell{:});
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.PlanID = obj.PlanID;
            strObj.Header = saveobj(obj.Header);
            strObj.Locations = arrayfun(@(x) saveobj(x), obj.Locations);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.ropod_ros_msgs.ropod_demo_plan.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.ropod_ros_msgs.ropod_demo_plan;
            obj.reload(strObj);
        end
    end
end
