classdef ropod_demo_status < robotics.ros.Message
    %ropod_demo_status MATLAB implementation of ropod_ros_msgs/ropod_demo_status
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2018 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'ropod_ros_msgs/ropod_demo_status' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '4be78bc21cbb110041997da1fc121888' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        Status
        SequenceNumber
        TotalNumber
    end
    
    properties (Constant, Hidden)
        PropertyList = {'SequenceNumber', 'Status', 'TotalNumber'} % List of non-constant message properties
        ROSPropertyList = {'sequenceNumber', 'status', 'totalNumber'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = ropod_demo_status(msg)
            %ropod_demo_status Construct the message object ropod_demo_status
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function status = get.Status(obj)
            %get.Status Get the value for property Status
            status = char(obj.JavaMessage.getStatus);
        end
        
        function set.Status(obj, status)
            %set.Status Set the value for property Status
            validateattributes(status, {'char'}, {}, 'ropod_demo_status', 'Status');
            
            obj.JavaMessage.setStatus(status);
        end
        
        function sequencenumber = get.SequenceNumber(obj)
            %get.SequenceNumber Get the value for property SequenceNumber
            sequencenumber = typecast(int16(obj.JavaMessage.getSequenceNumber), 'uint16');
        end
        
        function set.SequenceNumber(obj, sequencenumber)
            %set.SequenceNumber Set the value for property SequenceNumber
            validateattributes(sequencenumber, {'numeric'}, {'nonempty', 'scalar'}, 'ropod_demo_status', 'SequenceNumber');
            
            obj.JavaMessage.setSequenceNumber(sequencenumber);
        end
        
        function totalnumber = get.TotalNumber(obj)
            %get.TotalNumber Get the value for property TotalNumber
            totalnumber = typecast(int16(obj.JavaMessage.getTotalNumber), 'uint16');
        end
        
        function set.TotalNumber(obj, totalnumber)
            %set.TotalNumber Set the value for property TotalNumber
            validateattributes(totalnumber, {'numeric'}, {'nonempty', 'scalar'}, 'ropod_demo_status', 'TotalNumber');
            
            obj.JavaMessage.setTotalNumber(totalnumber);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.Status = obj.Status;
            cpObj.SequenceNumber = obj.SequenceNumber;
            cpObj.TotalNumber = obj.TotalNumber;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Status = strObj.Status;
            obj.SequenceNumber = strObj.SequenceNumber;
            obj.TotalNumber = strObj.TotalNumber;
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Status = obj.Status;
            strObj.SequenceNumber = obj.SequenceNumber;
            strObj.TotalNumber = obj.TotalNumber;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.ropod_ros_msgs.ropod_demo_status.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.ropod_ros_msgs.ropod_demo_status;
            obj.reload(strObj);
        end
    end
end
