classdef ropod_demo_location < robotics.ros.Message
    %ropod_demo_location MATLAB implementation of ropod_ros_msgs/ropod_demo_location
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2014-2018 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'ropod_ros_msgs/ropod_demo_location' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = '6cfaf6023f494ea34fea2392f950922c' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Constant, Access = protected)
        RopodRosMsgsRopodDemoAreaClass = robotics.ros.msg.internal.MessageFactory.getClassForType('ropod_ros_msgs/ropod_demo_area') % Dispatch to MATLAB class for message type ropod_ros_msgs/ropod_demo_area
        RopodRosMsgsRopodDemoStatusClass = robotics.ros.msg.internal.MessageFactory.getClassForType('ropod_ros_msgs/ropod_demo_status') % Dispatch to MATLAB class for message type ropod_ros_msgs/ropod_demo_status
    end
    
    properties (Dependent)
        Command
        LocationName
        Id
        LocationStatus
        Areas
    end
    
    properties (Access = protected)
        Cache = struct('LocationStatus', [], 'Areas', []) % The cache for fast data access
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Areas', 'Command', 'Id', 'LocationName', 'LocationStatus'} % List of non-constant message properties
        ROSPropertyList = {'areas', 'command', 'id', 'locationName', 'locationStatus'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = ropod_demo_location(msg)
            %ropod_demo_location Construct the message object ropod_demo_location
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function command = get.Command(obj)
            %get.Command Get the value for property Command
            command = char(obj.JavaMessage.getCommand);
        end
        
        function set.Command(obj, command)
            %set.Command Set the value for property Command
            validateattributes(command, {'char'}, {}, 'ropod_demo_location', 'Command');
            
            obj.JavaMessage.setCommand(command);
        end
        
        function locationname = get.LocationName(obj)
            %get.LocationName Get the value for property LocationName
            locationname = char(obj.JavaMessage.getLocationName);
        end
        
        function set.LocationName(obj, locationname)
            %set.LocationName Set the value for property LocationName
            validateattributes(locationname, {'char'}, {}, 'ropod_demo_location', 'LocationName');
            
            obj.JavaMessage.setLocationName(locationname);
        end
        
        function id = get.Id(obj)
            %get.Id Get the value for property Id
            id = char(obj.JavaMessage.getId);
        end
        
        function set.Id(obj, id)
            %set.Id Set the value for property Id
            validateattributes(id, {'char'}, {}, 'ropod_demo_location', 'Id');
            
            obj.JavaMessage.setId(id);
        end
        
        function locationstatus = get.LocationStatus(obj)
            %get.LocationStatus Get the value for property LocationStatus
            if isempty(obj.Cache.LocationStatus)
                obj.Cache.LocationStatus = feval(obj.RopodRosMsgsRopodDemoStatusClass, obj.JavaMessage.getLocationStatus);
            end
            locationstatus = obj.Cache.LocationStatus;
        end
        
        function set.LocationStatus(obj, locationstatus)
            %set.LocationStatus Set the value for property LocationStatus
            validateattributes(locationstatus, {obj.RopodRosMsgsRopodDemoStatusClass}, {'nonempty', 'scalar'}, 'ropod_demo_location', 'LocationStatus');
            
            obj.JavaMessage.setLocationStatus(locationstatus.getJavaObject);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.LocationStatus)
                obj.Cache.LocationStatus.setJavaObject(locationstatus.getJavaObject);
            end
        end
        
        function areas = get.Areas(obj)
            %get.Areas Get the value for property Areas
            if isempty(obj.Cache.Areas)
                javaArray = obj.JavaMessage.getAreas;
                array = obj.readJavaArray(javaArray, obj.RopodRosMsgsRopodDemoAreaClass);
                obj.Cache.Areas = feval(obj.RopodRosMsgsRopodDemoAreaClass, array);
            end
            areas = obj.Cache.Areas;
        end
        
        function set.Areas(obj, areas)
            %set.Areas Set the value for property Areas
            if ~isvector(areas) && isempty(areas)
                % Allow empty [] input
                areas = feval([obj.RopodRosMsgsRopodDemoAreaClass '.empty'], 0, 1);
            end
            
            validateattributes(areas, {obj.RopodRosMsgsRopodDemoAreaClass}, {'vector'}, 'ropod_demo_location', 'Areas');
            
            javaArray = obj.JavaMessage.getAreas;
            array = obj.writeJavaArray(areas, javaArray, obj.RopodRosMsgsRopodDemoAreaClass);
            obj.JavaMessage.setAreas(array);
            
            % Update cache if necessary
            if ~isempty(obj.Cache.Areas)
                obj.Cache.Areas = [];
                obj.Cache.Areas = obj.Areas;
            end
        end
    end
    
    methods (Access = protected)
        function resetCache(obj)
            %resetCache Resets any cached properties
            obj.Cache.LocationStatus = [];
            obj.Cache.Areas = [];
        end
        
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Clear any existing cached properties
            cpObj.resetCache;
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.Command = obj.Command;
            cpObj.LocationName = obj.LocationName;
            cpObj.Id = obj.Id;
            
            % Recursively copy compound properties
            cpObj.LocationStatus = copy(obj.LocationStatus);
            cpObj.Areas = copy(obj.Areas);
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Command = strObj.Command;
            obj.LocationName = strObj.LocationName;
            obj.Id = strObj.Id;
            obj.LocationStatus = feval([obj.RopodRosMsgsRopodDemoStatusClass '.loadobj'], strObj.LocationStatus);
            AreasCell = arrayfun(@(x) feval([obj.RopodRosMsgsRopodDemoAreaClass '.loadobj'], x), strObj.Areas, 'UniformOutput', false);
            obj.Areas = vertcat(AreasCell{:});
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Command = obj.Command;
            strObj.LocationName = obj.LocationName;
            strObj.Id = obj.Id;
            strObj.LocationStatus = saveobj(obj.LocationStatus);
            strObj.Areas = arrayfun(@(x) saveobj(x), obj.Areas);
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.ropod_ros_msgs.ropod_demo_location.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.ropod_ros_msgs.ropod_demo_location;
            obj.reload(strObj);
        end
    end
end
